[build]
  command = "echo 'Build process not required'"  # Não é necessário processo de build
  publish = "."  # Diretório de publicação

[[headers]]
  for = "/*.html"
    [headers.values]
    Content-Type = "text/html"

[[headers]]
  for = "/css/*"
    [headers.values]
    Content-Type = "text/css"