# Generated by Django 5.0.1 on 2024-02-16 01:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filme', '0002_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='filme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video', to='filme.filme'),
        ),
    ]
