# Generated by Django 5.0.2 on 2024-03-11 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filme', '0004_video_trailer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filme',
            name='categoria',
            field=models.CharField(choices=[('acao', 'Ação'), ('animacao', 'Animação'), ('comedia', 'Comedia'), ('ficcao', 'Ficção científica'), ('suspense', 'Suspense'), ('terror', 'Terror'), ('drama', 'Drama'), ('romance', 'Romance'), ('documentario', 'Documentario')], max_length=15),
        ),
    ]
