# Generated by Django 5.0.2 on 2024-03-11 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filme', '0005_alter_filme_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Videotv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('thumb_tv', models.ImageField(upload_to='thumb_tv')),
                ('video', models.URLField()),
            ],
        ),
    ]
