# Generated by Django 5.0.2 on 2024-03-11 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filme', '0006_videotv'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videotv',
            old_name='video',
            new_name='video_tv',
        ),
    ]
